### ISSUE TITLE
What json data should be passed onto STDIN when testing /opt/resource/out? 

### ISSUE THREAD

**Issue by dev-jin** [Pix4D/cogito#137]
Apologies in advance if this is not the right place to ask questions, but I know no other options. 

Within the cogito image, I'm trying to run the `/opt/resource/out` command by passing on a json data manually through STDIN for `PUT`. What is the exact format of the data that is required? I keep encountering some argument error from the json data. The task file looks like so:

```
---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((redacted))/cogito-gh-status-resource
    tag: ((redacted))
    username: ((redacted))
    password: ((redacted))
inputs:
  - name: git-source
run:
  path: sh
  args:
    - -exc
    - |
      /opt/resource/out . < git-source/instana-tasks-resource/ci/request-data/request-data-populated.json
```
