### ISSUE TITLE
Feature Request: Optional target_url

### ISSUE THREAD

**Issue by rfpludwick** [Pix4D/cogito#159]
I would love to be able to **optionally** set the target_url when setting the GH status. One of the Concourse CI systems I run is entirely private, but it does run pipelines for a public repository on GitHub. I'd like to be able to report build status, but without the URL as that is private information. Could define the optional target URL either in the resource configuration or on the `put`.

```yaml
    on_success:
      put: gh-status
      inputs: [the-repo]
      params: {state: success, target_url: false}

---

- name: gh-status
  type: cogito
  check_every: never
  source:
    owner: ((github-owner))
    repo: ((your-repo-name))
    access_token: ((github-PAT))
    target_url: false
```

**Comment by marco-m-pix4d** [comment]
Ah, I understand the reasoning. Makes sense. I appreciate that you proposed a possible and backwards compatible configuration for this.

My first reaction is wondering if there is a way to make the intent more explicit. For example: `omit_target_url (bool)`. In any case, this is a nitpick.

**Comment by marco-m-pix4d** [comment]
@rfpludwick I discussed with the team and we think it is a reasonable request. Would you be interested in proposing a PR?

**Comment by rfpludwick** [comment]
@marco-m-pix4d I can give it a try. My Go experience isn't super deep, but I think I can muddle my way through to an acceptable PR eventually.

**Comment by marco-m-pix4d** [comment]
I had some time and went ahead with #160.

**Comment by rfpludwick** [comment]
Ah fantastic! Thanks @marco-m-pix4d!

**Comment by marco-m-pix4d** [comment]
@rfpludwick I pushed a Docker image with tag `omit-target-url`.

Could you please check it with the following configuration?

```
resource_types:
- name: cogito
  type: registry-image
  check_every: 24h
  source:
    repository: pix4d/cogito
    tag: omit-target-url
```

**NOTE** the Docker image with tag: omit-target-url is **short-lived**, do not rely on its presence. Once you confirm that it works, I will issue a new Cogito release and at this point you should remove the `tag` line from the configuration.
